apiVersion: v1
kind: Service
metadata:
  name: {{ include "openviking.fullname" . }}
  labels:
    {{- include "openviking.labels" . | nindent 4 }}
  annotations:
    {{- include "openviking.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "openviking.selectorLabels" . | nindent 4 }}
